apiVersion: v1
kind: Service
metadata:
  name: kong-validation-webhook
  namespace: kong
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingress-kong
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: kong
spec:
  clusterIP: None
  ports:
  - name: admin
    port: 8444
    protocol: TCP
    targetPort: 8444
  selector:
    app: proxy-kong
